### PR TITLE
DEV: Get HXRSnD to build, adding all our dev tools

### PR DESCRIPTION
**Pull request by apra93**
PR that fixes the requirements to allow HXRSnD to build. Also added `landscape.yml`, and set all the dev tools to ignore attocube_testing. Added badges to the readme.

I also had to set an initial state in `test_states.py` for it to run properly.

### CODE REVIEW

**Comment by teddyrendahl** [comment]
@apra93 Can you check what package versions are being used for `super_state_machine`. It runs fine on my checkout?

**Comment by apra93** [comment]
@teddyrendahl I've been using `2.0.2`. Looking at the travis builds, it seems to be using `1.0-py35h31ba8cf_0` from `lightsource2-tag`.

`super_state_machine`'s docs say that having an empty state has been disallowed since version `2.0`, so most likely lightsource is using an older build, or they've set `allow_empty`  to be `True` by default.

Is there anything special about `super_state_machine` built by `lightsource2-tag`?

**Comment by teddyrendahl** [comment]
I don't know what is special, but I know we should probably have that one if we are going to use it for  bluesky. I'm not sure how we are even getting a different version?

Also can you add `pswalker` to `requirements.txt`. We will need it soon enough ...

**Comment by apra93** [comment]
Just checked and it turns out they use version `1.0`. I'll remove the `initial_state` line in the tests, just keep in mind that if it starts randomly failing in the future it might be because they updated the dependency.

And yeah I'll add `pswalker`

**Pull request merged**
