### PR TITLE
DOC: First pass at documentation

### PR DESCRIPTION
**Pull request by apra93**
## Description

Made a first pass at adding documentation for the project. It has all the documentation written thus far split up into sections that make sense to me but is totally open to changes. It still needs to be set up with a place to host them, but that will come in a future PR.

### CODE REVIEW

**Comment by ZLLentz** [comment]
@apra93 I saw the `MAINT: Adding pswalker deps that arent in the pcds env` commit message. Did I make a mistake in building the env?

**Comment by apra93** [comment]
@ZLLentz I'm just seeing this now, its just our other slac modules (`lightpath`, `happi` and `psbeam`)

**Comment by teddyrendahl** [comment]
@apra93 We put these in a new release `pcds-0.3.0`!

**Comment by apra93** [comment]
@ZLLentz I'll make the change!

**Pull request merged**
